### POST request to create service messages
POST localhost:3000/api/v1/nemdeling/service-messages
Content-Type: application/xml

<result is_array="true">
    <item>
        <field_display_institution is_array="true">
            <item>hus1</item>
        </field_display_institution>
        <nid>4</nid>
        <title_field>test213-new6</title_field>
        <field_background_color>#2e4f2a</field_background_color>
        <body>dette er en test - new</body>
        <field_os2_display_list_spot is_array="true">
            <item>screen_1</item>
            <item>screen_2</item>
        </field_os2_display_list_spot>
    </item>
    <item>
        <field_display_institution is_array="true">
            <item>
            </item>
        </field_display_institution>
        <nid>5</nid>
        <title_field>test4324234</title_field>
        <field_background_color>#ffffff</field_background_color>
        <body>dette er en test</body>
        <field_os2_display_list_spot is_array="true">
            <item>
            </item>
        </field_os2_display_list_spot>
    </item>
    <item>
        <field_display_institution is_array="true">
            <item>
            </item>
        </field_display_institution>
        <nid>6</nid>
        <title_field>Test title 1</title_field>
        <field_background_color>#ffffff</field_background_color>
        <body>Test test</body>
        <field_os2_display_list_spot is_array="true">
            <item>screen_1</item>
        </field_os2_display_list_spot>
    </item>
</result>
