### POST request to create service messages
POST localhost:3000/api/v1/nemdeling/service-messages
Content-Type: application/xml

<result is_array="true">
    <item>
        <field_display_institution is_array="true">
            <item>hus1</item>
        </field_display_institution>
        <nid>4</nid>
        <title_field>test213-new6</title_field>
        <field_background_color>#2e4f2a</field_background_color>
        <body>This is a short\n test\r\nThis is a newline\r\nThis is another line\n, this should be on it's own line.</body>
        <field_os2_display_list_spot is_array="true">
            <item>screen_1</item>
            <item>screen_2</item>
        </field_os2_display_list_spot>
    </item>
    <item>
        <field_display_institution is_array="true">
            <item>
            </item>
        </field_display_institution>
        <nid>5</nid>
        <title_field>test4324234</title_field>
        <field_background_color>#ffffff</field_background_color>
        <body>dette er en test</body>
        <field_os2_display_list_spot is_array="true">
            <item>
            </item>
        </field_os2_display_list_spot>
    </item>
    <item>
        <field_display_institution is_array="true">
            <item>
            </item>
        </field_display_institution>
        <nid>6</nid>
        <title_field>Test title 1</title_field>
        <field_background_color>#ffffff</field_background_color>
        <body>Test test</body>
        <field_os2_display_list_spot is_array="true">
            <item>screen_1</item>
        </field_os2_display_list_spot>
    </item>
</result>

### POST request to create events
POST localhost:3000/api/v1/nemdeling/events
Content-Type: application/xml

<result is_array="true">
    <item>
        <startdate is_array="true">
            <item>21.10.2022</item>
        </startdate>
        <enddate is_array="true">
            <item>21.10.2022</item>
        </enddate>
        <time is_array="true">
            <item>19:00 til 20:30</item>
        </time>
        <Nid>140</Nid>
        <billede is_array="true">
            <item>
                <img src="https://union.kk.dk/sites/default/files/2022-08/IMG_20220507_0036%201920x1080.jpg" alt="Yacarandá besøger Union 21. oktober 2022" height="1080" width="1920" title="" />
            </item>
        </billede>
        <title>Yacarandá (BRA/BOL/ARG) at Union</title>
        <field_teaser>Elegante og skrøbelige melodier, der blander brasiliansk folklore, klassisk musik og afrobrasilianske rytmer.</field_teaser>
        <screen is_array="true">
            <item>copenhagen_test</item>
            <item>screen_3</item>
            <item>screen_4</item>
        </screen>
        <host>Uni på højen</host>
        <bgColor>#333542</bgColor>
    </item>
    <item>
        <startdate is_array="true">
            <item>02.09.2022</item>
        </startdate>
        <enddate is_array="true">
            <item>02.09.2022</item>
        </enddate>
        <time is_array="true">
            <item>12:00 til 12:00</item>
        </time>
        <Nid>62</Nid>
        <billede is_array="true">
            <item>
                <img src="https://union.kk.dk/sites/default/files/2021-12/DanielLiversage_Union_Kulturnat-47_1200x554_0.jpg" alt="Fuse Jam hver søndag i Union" height="554" width="1200" title="" />
            </item>
        </billede>
        <title>Fuse Point Jam </title>
        <field_teaser>Beginner friendly dance workshop and open dancefloor.</field_teaser>
        <screen is_array="true">
            <item>copenhagen_test</item>
            <item>screen_2</item>
        </screen>
        <host></host>
        <bgColor>test</bgColor>
    </item>
</result>

### POST request to create event lists
POST localhost:3000/api/v1/nemdeling/event-lists
Content-Type: application/xml

<result is_array="true">
    <item>
        <startdate is_array="true">
            <item>21.10.2022</item>
        </startdate>
        <enddate is_array="true">
            <item>21.10.2022</item>
        </enddate>
        <time is_array="true">
            <item>19:00 til 20:30</item>
        </time>
        <Nid>140</Nid>
        <billede is_array="true">
            <item>
                <img src="https://union.kk.dk/sites/default/files/2022-08/IMG_20220507_0036%201920x1080.jpg" alt="Yacarandá besøger Union 21. oktober 2022" height="1080" width="1920" title="" />
            </item>
        </billede>
        <title>Yacarandá (BRA/BOL/ARG) at Union</title>
        <field_teaser>Elegante og skrøbelige melodier, der blander brasiliansk folklore, klassisk musik og afrobrasilianske rytmer.</field_teaser>
        <screen is_array="true">
            <item>copenhagen_test</item>
            <item>screen_3</item>
            <item>screen_4</item>
        </screen>
        <host>Uni på højen</host>
        <bgColor>#333542</bgColor>
    </item>
    <item>
        <startdate is_array="true">
            <item>02.09.2022</item>
        </startdate>
        <enddate is_array="true">
            <item>02.09.2022</item>
        </enddate>
        <time is_array="true">
            <item>12:00 til 12:00</item>
        </time>
        <Nid>62</Nid>
        <billede is_array="true">
            <item>
                <img src="https://union.kk.dk/sites/default/files/2021-12/DanielLiversage_Union_Kulturnat-47_1200x554_0.jpg" alt="Fuse Jam hver søndag i Union" height="554" width="1200" title="" />
            </item>
        </billede>
        <title>Fuse Point Jam </title>
        <field_teaser>Beginner friendly dance workshop and open dancefloor.</field_teaser>
        <screen is_array="true">
            <item>copenhagen_test</item>
            <item>screen_2</item>
        </screen>
        <host></host>
        <bgColor>test</bgColor>
    </item>
</result>

### POST request to create event themes
POST localhost:3000/api/v1/nemdeling/event-theme
Content-Type: application/xml

<result is_array="true">
    <item>
        <startdate is_array="true">
            <item>29.04.2023</item>
        </startdate>
        <enddate is_array="true">
            <item>30.04.2023</item>
        </enddate>
        <time is_array="true">
            <item>20:00 til 01:00</item>
        </time>
        <Nid>82</Nid>
        <billede is_array="true">
            <item>
                <img src="https://basement.kk.dk/sites/default/files/2022-09/web.png" alt="" height="554" width="1200" title="" />
            </item>
        </billede>
        <title>Ian Person (SE)</title>
        <field_teaser>Ian Person, tidligere guitarist og sangskriver i Union Carbide Productions og The Soundtrack Of Our Lives, udgiver sit andet soloalbum i foråret 2023 og lægger i den forbindelse vejen forbi København.</field_teaser>
        <screen is_array="true">
            <item>tematest</item>
        </screen>
        <alternativ_titel>Rock</alternativ_titel>
        <titel>Alternativ titel</titel>
        <host>Bøhlandet</host>
        <farvepar>farvepar2</farvepar>
    </item>
</result>
